import gym
from conformer_rl.environments.curriculum_conformer_env import CurriculumConformerEnv
from conformer_rl.environments.environment_components.action_mixins import DiscreteActionMixin
from conformer_rl.environments.environment_components.obs_mixins import AtomCoordsTypeGraphObsMixin
from conformer_rl.environments.environment_components.reward_mixins import GibbsPruningRewardMixin

class CurriculumEnv(GibbsPruningRewardMixin, AtomCoordsTypeGraphObsMixin, DiscreteActionMixin, CurriculumConformerEnv):
    pass

gym.register(id='CurriculumEnv-v0', entry_point='curriculum_env:CurriculumEnv')