from .A2C import A2CAgent, A2CRecurrentAgent
from .PPO import PPOAgent, PPORecurrentAgent

from .curriculum_agents import A2CExternalCurriculumAgent, A2CRecurrentExternalCurriculumAgent
from .curriculum_agents import PPOExternalCurriculumAgent, PPORecurrentExternalCurriculumAgent